package vip.mate.analytics.controller;

import jakarta.servlet.http.HttpServletResponse;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RestController;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Serves xlsx export files generated by {@link vip.mate.analytics.tool.AnalyticsExportTool}.
 *
 * <p>Files are read from the system temp directory. The filename is validated to contain
 * only safe characters before path construction to prevent directory traversal.
 */
@RestController
public class ExportDownloadController {

    /** Only alphanumeric, hyphen, underscore, and dot are permitted in export filenames. */
    private static final String SAFE_FILENAME_PATTERN = "[a-zA-Z0-9._-]+";

    /**
     * Downloads an analytics export file by filename.
     *
     * @param filename the temp file name (no path separators allowed)
     * @param response the HTTP response to stream the file into
     */
    @GetMapping("/api/analytics/exports/{filename}")
    public void download(
            @PathVariable String filename,
            HttpServletResponse response) throws IOException {

        if (!filename.matches(SAFE_FILENAME_PATTERN)) {
            response.sendError(400);
            return;
        }

        Path file = Path.of(System.getProperty("java.io.tmpdir"), filename);
        if (!Files.exists(file)) {
            response.sendError(404);
            return;
        }

        response.setContentType("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
        response.setHeader("Content-Disposition", "attachment; filename=\"" + filename + "\"");
        Files.copy(file, response.getOutputStream());
    }
}
